name: ⚠️ Bug
description: Report an issue with the project.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue you have encountered.
    validations:
      required: true
    - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce?
      description: How to reproduce the issue?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots.
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our [Discord community](http://discord.gg/NXYbv4dnYQ)
