name: Report an issue.
description: Submit a report regarding any problems or issues with the project.
labels: ["bug"]
body:
  - type: textarea
    id: current
    attributes:
      label: What is the current behavior?
      description: Could you explain how the issue is currently behaving?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is the expected behavior?
      description: Could you explain how the issue should behave?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Could you share screenshots?
      description: Are there any relevant screenshots or videos that you can provide?
    validations:
      required: false
  - type: textarea
    id: extra-info
    attributes:
      label: Could you provide additional information?
      description: Is there any additional information that might be relevant to the issue?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our [Discord community](http://discord.gg/NXYbv4dnYQ)
